name: m2pcarddetails
description: To be able to show a card details.
version: 0.0.1
homepage: https://Mariganesh55@bitbucket.org/Mariganesh55/m2pcarddetails.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  equatable: ^2.0.0
  dio: ^3.0.10
  json_annotation: ^3.1.1
  fluttertoast: ^7.1.8
  pin_code_fields: ^7.0.0
  intl: ^0.17.0
  local_auth: ^1.1.5
  flutter:
    sdk: flutter 
  


    

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec




# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - packages/m2pcarddetails/assets/images/cancel.png
    - packages/m2pcarddetails/assets/images/master.png
    - packages/m2pcarddetails/assets/images/copy.png
    - packages/m2pcarddetails/assets/images/cardBg.png
    - packages/m2pcarddetails/assets/images/tenetBg.png
    - packages/m2pcarddetails/assets/images/Waves.png
    - packages/m2pcarddetails/assets/images/blockCard.png
    - packages/m2pcarddetails/assets/images/cardPreference.png
    - packages/m2pcarddetails/assets/images/setpin.png
    - packages/m2pcarddetails/assets/images/downArrow.png
    - packages/m2pcarddetails/assets/images/upArrow.png
    - packages/m2pcarddetails/assets/images/otp.png
    - packages/m2pcarddetails/assets/images/tick.png
    - packages/m2pcarddetails/assets/images/blockCardConformation.png
    - packages/m2pcarddetails/assets/images/lock.png
    - packages/m2pcarddetails/assets/images/unlock.png
    - packages/m2pcarddetails/assets/images/atm.png
    - packages/m2pcarddetails/assets/images/ecom.png
    - packages/m2pcarddetails/assets/images/pos.png
    - packages/m2pcarddetails/assets/images/edit.png
    
    
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ilisarniq-Black
      fonts:
        - asset: packages/m2pcarddetails/assets/fonts/Ilisarniq-Black.ttf
    - family: Ilisarniq-BlackItalic
      fonts:
        - asset: packages/m2pcarddetails/assets/fonts/Ilisarniq-BlackItalic.ttf
    - family: Ilisarniq-Bold
      fonts:
        - asset: packages/m2pcarddetails/assets/fonts/Ilisarniq-Bold.ttf
    - family: Ilisarniq-BoldItalic
      fonts:
        - asset: packages/m2pcarddetails/assets/fonts/Ilisarniq-BoldItalic.ttf
    - family: Ilisarniq-Demi
      fonts:
        - asset: packages/m2pcarddetails/assets/fonts/Ilisarniq-Demi.ttf
    - family: Ilisarniq-DemiItalic
      fonts:
        - asset: packages/m2pcarddetails/assets/fonts/Ilisarniq-DemiItalic.ttf
    - family: Ilisarniq-Italic
      fonts:
        - asset: packages/m2pcarddetails/assets/fonts/Ilisarniq-Italic.ttf
    - family: Ilisarniq-Light
      fonts:
        - asset: packages/m2pcarddetails/assets/fonts/Ilisarniq-Light.ttf
    - family: Ilisarniq-LightItalic
      fonts:
        - asset: packages/m2pcarddetails/assets/fonts/Ilisarniq-LightItalic.ttf
    - family: Ilisarniq-Regular
      fonts:
        - asset: packages/m2pcarddetails/assets/fonts/Ilisarniq-Regular.ttf                            
      
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
